apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webpage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/davidlimacardoso/demo-argocd
    path: k8s/webpage
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
